### PR TITLE
Bluepay hosted + Bank transfer update

### PR DESCRIPTION
**Pull request by gob33**

### CODE REVIEW

**Comment by villagedefrance** [comment]
Thanks, but please be more careful next time because this pull request has deleted the entire "install" folder!

**Comment by gob33** [comment]
I have difficulties with that "#*$:?# github.
Tons of english words i dont understand when merging master with your changes and my changes.

**Comment by villagedefrance** [comment]
No problem. I have recovered it.
It is my fault too because I didn't check the files fully before merging.

**Comment by gob33** [comment]
This is due to the procedure in upload\admin\controller\common\home.php
who deletes install dir each times I go in test.
Then it has passed in my big commits.

**Comment by skyosev** [comment]
@gob33, 

This automatic deletion is really annoying. That's why I have a working opencart directory and another one for github commits only (bare repository). When I finish a feature in the working dir, I transfer the changes to the bare repository with a diff/merge tool and the commit from there.

**Comment by gob33** [comment]
But its easier to test directly on the fly when you make many small changes.
I will put automatic deletion in comments or install dir in gitignore.

**Pull request merged**
