### PR TITLE
Canonicals & pagination

### PR DESCRIPTION
**Pull request by dhaupin**
Hi guys, here is another pull that can help your OC build SEO:

 - Adds canonicals to categories, mfg, and information pages
 - Refactors pagination class a bit to allow rel's which reflect https://support.google.com/webmasters/answer/1663744?hl=en
 - Let's say you are on page 2 of a category. Rel prev would say page 1, rel next would say page 3, canonical would change to page 2 (yes this is correct that each page is canonical as per that doc)
 - Fixes pagination UX to be more intuitive (no need for most of those nav buttons)
 - Re-words the "results" string so that Google can parse it and include in SERP
 - Limit enforcer to prevent bot DOS when they try to request 250 items per page (or 0 items per page....yandex....) You can move this if you like, but i preferred it first in function so that other calls for limit are re-written in time.

1 merge ahead because i synced in UI. Demo running here: https://___.cjshearthandhome.com/src/_OV

Thanks!

### CODE REVIEW

**Comment by dhaupin** [comment]
Sorry about the reverts on those 2 commits :) I know thats annoying ....

**Comment by villagedefrance** [comment]
Thanks, that's a biggy! I'll try to go through it all but I'm confident you checked everything already.

**Comment by dhaupin** [comment]
Thanks. Def check it out-- these are important for ecom list views. These have been production for ~8 months in our stores with SERP resilience (the pager there sticks and generally G goes page 1). If you find issues with performance/meththodstyle or got ideas for a better way, lets make it!

**Comment by villagedefrance** [comment]
If ATOM feeds are for products then I am interested. I would like to upgrade the current "Product RSS Feed" because it is far from perfect. Maybe when you got a minute, no rush.

**Pull request merged**
