### PR TITLE
Paypal Express update + some Payflow corrections

### PR DESCRIPTION
**Pull request by gob33**
I changed a lot but kept OC2.x main code.
Needs some tests i cant do because new security Paypal protocol uses TLS1.2 (PHP 5.5.19+ and curl 7.29+) and i am in php5.4
I modified some recurring too.
It is heavy and lost myself inside.

### CODE REVIEW

**Comment by villagedefrance** [comment]
I always appreciate your hard work on payment methods, but this time I probably won't merge it.
My OCE current PP Express is still valid and not as demanding as the OC 2.x version, and the current PHP minimum requirements for OCE are quite fine with PHP 5.4. I do not want to change that. Also, many OC v2.x users are very unhappy with this version of PP Express (see forums).
So unless it is fully tested, I will not merge it.
Merry Christmas :)

**Comment by gob33** [comment]
With Paypal progressively installing new security standarts (HTTP/1.1, TLS 1.2 and SHA-256 certificates), you will need a version of cURL that supports TLS1.2 and a higher PHP version than 5.4 as it is bound to.

Your current OCE PP Express is outdated, it doesnt had sandbox username,pass, signature; the checkout color customization has changed since.
I have added many errors handlings as OC2.x pass silently in many cases.
Rewrote refund() and recurringcancel() + many inconsistencies.
I have checked as much as possible without Paypal connection, by using hard code response messages.
I didnt succed with Sandbox (TLS1.2) as my PHP is 5.4
I agree it needs real testing.

**Comment by gob33** [comment]
And it is the same for Paypal Pro Iframe, it needs complete revision.
The code is a collection of modifications done by different people.

**Comment by villagedefrance** [comment]
Ok, I'm going to merge it.
First, because I trust your expertise and your work.
Second, because we can't go against progress.
Still, I am going to keep PHP 5.4 as the minimum, but possibly add a mention in PP Express admin to tell users about the server's requirements if they choose to use it.

**Comment by gob33** [comment]
Ah ok good. I can go further in payment corrections.
Keep PHP 5.4 for the moment.
Im in Win XP, to upgrade PHP i will need to go to Win 7.1 for Wamp to operate

I think the new Paypal standard (HTTP/1.1, TLS 1.2 and SHA-256 certificates) will be completely operational in Jan 1, 2018. They have a roadmap to deploy progressively. The Sandbox API endpoints only support new standard since Jan 14, 2016.

**Pull request merged**
