### PR TITLE
Affiliate (admin part)

### PR DESCRIPTION
**Pull request by gob33**

### CODE REVIEW

**Comment by gob33** [comment]
Wait for my approval for merging because the 'caralog' part is unfinished on oc2.x

**Comment by villagedefrance** [comment]
Ok, I will wait ...

**Comment by gob33** [comment]
I encounters many difficulties as some settings and methods in oc2.x leaks in overclocked.
And each method is chained to another, and new things have been introduced, etc...

**Comment by villagedefrance** [comment]
I understand. OC 2.x is becoming very complicated and this is one of the reasons I decided to base Overclocked on v1.5.6.4, ... much simpler.
I think the best way to do this is to strip the new features out individually from v2.x and adapt them into Overclocked, instead of converting whole files.
If it is too hard, no worries, just delete the pull request.

**Comment by gob33** [comment]
The more i progress, the more I highly doubt about the fiability of affiliates (and specially the transactions).
This extension has simplified all into a single account, which seems far better:
http://www.opencart.com/index.php?route=extension/extension/info&extension_id=8862

**Comment by villagedefrance** [comment]
Yup, but this is a commercial extension :( and I doubt its developer will be willing to see it integrated for free.
I am going to have a look and maybe I can add a few new affiliate features myself.
As always, thanks for your efforts.

**Comment by gob33** [comment]
Now you can try to patch.
I could have forgotten some pieces (new settings in .sql files). Will re-check after.
Also the code differ more and more from oc2.x, so that i becomes difficult to find the same passages of text.

**Pull request merged**
