### PR TITLE
Worldpay online payments

### PR DESCRIPTION
**Pull request by gob33**
Read opencart issue #3207
I renamed it to 'worldpay_online' to keep also the old method Worldpay Business with form in case of...

### CODE REVIEW

**Comment by gob33** [comment]
I should have called these 'worldpay_hosted' and 'worldpay_redirect' to be consistant with bluepay..

**Comment by gob33** [comment]
Updated Web payment software

**Comment by gob33** [comment]
Updated twocheckout

**Comment by villagedefrance** [comment]
Sorry, I cannot merge at this time.
I made too many changes and added some of your commits already..
Any chance of submitting them again? in smaller chunks maybe?

**Comment by skyosev** [comment]
I.e. you should rebase.

**Comment by gob33** [comment]
Absolutely not familiar with github.
I can delete my repository, merge master in local and then re-push local ?

**Comment by villagedefrance** [comment]
Thanks guys, merged it!

**Pull request merged**
